### ISSUE TITLE
Drive link is missing

### ISSUE THREAD

**Issue by hanumantmule** [satwik-m/Video-Captioning-with-Bi-LSTM-and-Attention#1]
Hey Satwik,
The readme file, you talked about drive link shared has all the required files including MSVD datasets, glove word embeddings, train-test split, saved models, and generated results.

Could you please share the drive link where I get the MSVD datasets, glove word embeddings, train-test split, saved models and generated results.

**Comment by aadilkhalifa** [comment]
Hey @hanumantmule 
Were you able to get the drive link?
